### ISSUE TITLE
[feat] Add validation toolkit

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks-Challenges/cnb-tools#25]
## Describe The Problem To Be Solved
Add common checks for validation, e.g.
- check for missing values
- check for unknown values
- check for duplicated values

etc.

## (optional) Suggest a Solution
Extract and generalize existing validation scripts, e.g. preterm birth, PEGS, etc.

**Comment by thomasyu888** [comment]
This may be over engineering the solution, but you may want to look at great expectations.

We have been using it more across all our projects at sage for data validation.

**Comment by vpchung** [comment]
I'll explore it, thanks!  From a quick glance though, I think GX does a lot more than what is needed here.
